from decimal import Decimal
from app.models import SellerPolicy, BulkRule, BulkTier
from app.deal_validator import DealConsistencyValidator, DealValidationRequest
from app.policy_engine import PolicyEngine, PolicyEngineDecision


def run_validator_tests():
    print("Running Hardened Unit Tests for PolicyEngine & DealConsistencyValidator...\n")

    policy_fixed = SellerPolicy(
        product_id="prod_001",
        pricing_mode="fixed",
        listed_price=Decimal("100.00"),
        aspiration_price=Decimal("100.00"),
        target_price=Decimal("100.00"),
        reservation_price=Decimal("100.00"),
        batna="normal_sale",
        max_negotiation_rounds=0,
    )

    policy_neg = SellerPolicy(
        product_id="prod_003",
        pricing_mode="negotiable",
        listed_price=Decimal("2500.00"),
        aspiration_price=Decimal("2400.00"),
        target_price=Decimal("1750.00"),
        reservation_price=Decimal("1550.00"),
        batna="normal_sale",
        max_negotiation_rounds=5,
    )

    # TEST A: Round-1 Lowball (Offer 1200) -> NOT accepted, counter generated by PolicyEngine, no floor leak
    dec_a = PolicyEngine.evaluate_offer(policy_neg, Decimal("1200.00"), round_number=1)
    assert not dec_a.accepted
    assert dec_a.seller_authorized_price > Decimal("1750.00")
    assert "1550" not in dec_a.buyer_safe_explanation
    print(f"[PASS] Test A: Round-1 lowball rejected. Controlled counter: Rs.{dec_a.seller_authorized_price:.2f}. No floor leak.")

    # TEST B: Round-1 Offer Just Above Floor (Offer 1600) -> NOT automatically accepted!
    dec_b = PolicyEngine.evaluate_offer(policy_neg, Decimal("1600.00"), round_number=1)
    assert not dec_b.accepted
    assert dec_b.seller_authorized_price > Decimal("1600.00")
    print(f"[PASS] Test B: Round-1 offer just above floor (Rs.1600) strictly NOT accepted. Counter: Rs.{dec_b.seller_authorized_price:.2f}.")

    # TEST C: Repeated Lowballs do NOT accelerate concessions to reservation floor
    counters_c = []
    for r in range(1, 6):
        d = PolicyEngine.evaluate_offer(policy_neg, Decimal("1000.00"), round_number=r)
        assert not d.accepted
        assert d.seller_authorized_price >= Decimal("1750.00")  # Never below target price!
        assert "1550" not in d.buyer_safe_explanation
        counters_c.append(d.seller_authorized_price)
    assert len(counters_c) == 5
    print(f"[PASS] Test C: Repeated lowballs maintained controlled counter schedule floored at target (Rs.1750): {counters_c}.")

    # TEST D: Strategic salesperson pacing (concedes slowly early, increases meaningfully later)
    # Verify step sizes grow or remain firm: (R1 - R2) <= (R2 - R3) <= (R3 - R4)
    step1_2 = counters_c[0] - counters_c[1]
    step2_3 = counters_c[1] - counters_c[2]
    step3_4 = counters_c[2] - counters_c[3]
    assert step1_2 <= step2_3 <= step3_4
    print(f"[PASS] Test D: Strategic salesperson pacing verified: concessions start small and grow meaningfully in later rounds (Steps: {step1_2:.2f}, {step2_3:.2f}, {step3_4:.2f}).")

    # TEST I: Fixed Product Negotiation Rejection
    dec_i = PolicyEngine.evaluate_offer(policy_fixed, Decimal("80.00"), round_number=1)
    assert not dec_i.accepted
    assert dec_i.seller_authorized_price == Decimal("100.00")
    print("[PASS] Test I: Fixed pricing mode strictly enforced (Counter: Rs.100.00).")

    print("\n[SUCCESS] ALL POLICY ENGINE & DEAL VALIDATOR UNIT TESTS PASSED CLEANLY!\n")


if __name__ == "__main__":
    run_validator_tests()
